site_name: Biosb Computational Metagenomics

# Repository
repo_url: https://github.com/mdehollander/biosb-metagenomics
repo_name: biosb-metagenomics

# Styling
theme:
  name: material
  custom_dir: docs/overrides
  features:
    - navigation.expand

# Navigation
nav:
  - Home: index.md
  - "Day 1: Data processing":
    - Introduction: data-processing/intro.md
    - Quality Control: data-processing/quality-control.md
    - Assembly: data-processing/assembly.md
    - Binning: data-processing/binning.md
    - Cave expedition: data-processing/cave-expedition.md
  - "Day 3: Functional annotation":
    - Viromics: functional-annotation/viromes.md
    - BGCs: functional-annotation/bgcs.md

markdown_extensions:
  - footnotes
  - meta
  - toc:
      permalink: true
  - admonition # Create info blocks for attention, abstract, bug, caution, danger, example, failure, info, hint, important, note, tip, success, question, quote, and warning
  - pymdownx.tilde
  - pymdownx.tabbed
  - pymdownx.keys
  - pymdownx.details #  collapsible admonition
  - admonition # Create info blocks for attention, abstract, bug, caution, danger, example, failure, info, hint, important, note, tip, success, question, quote, and warning
  - pymdownx.superfences # Styling code blocks, e.g. adding title
  - attr_list # Format buttons
  # Fontawesome icons
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
  - search
  - git-revision-date-localized
  - git-authors
